first = float(input("Enter the first number: "))
second = float(input ("Enter the second number: "))
third = float(input("Enter the third number: "))
print(first + second)
print(first + second + third)
print(first * third)
print(second / third)
print(third % second)
print((first + second) * 5)
